services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-orders
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-orders
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # UI RabbitMQ

  order-service:
    build: ./order-service
    container_name: order-service
    restart: always
    env_file: ./order-service/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - rabbitmq

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    env_file: ./payment-service/.env
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
